export const actionType = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  EMPTY_CART: "EMPTY_CART",
  GET_PRODUCT_LIST: "GET_PRODUCT_LIST",
  SET_PRODUCT_LIST: "SET_PRODUCT_LIST",
  SEARCH_PRODUCT: "SEARCH_PRODUCT",
};
